In [1]:
import tensorflow as tf
import keras

keras.__version__

'2.12.0'

In [2]:
tf.__version__

'2.12.0'

In [3]:
tf.config.experimental.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [4]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Activation
from tensorflow.keras.optimizers.legacy import SGD
import h5py

In [6]:
x_train = np.array([[2], [1], [-3]])
y_train = np.array([10, 5, -15])

In [7]:
num_neurons = 1
model = Sequential()
model.add(Dense(num_neurons, input_dim =1))
model.summary()

Metal device set to: Apple M1 Pro
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [8]:
sgd = SGD(learning_rate=1.0)
model.compile(loss='mean_squared_error', optimizer=sgd)

In [17]:
model.predict(x_train)

1/1 [==============================] - 0s 90ms/step


array([[ 10.964815 ],
       [  5.9648156],
       [-14.035185 ]], dtype=float32)

In [10]:
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
1/1 [==============================] - 0s 428ms/step - loss: 121.7697
Epoch 2/10
1/1 [==============================] - 0s 6ms/step - loss: 8456.2285
Epoch 3/10
1/1 [==============================] - 0s 6ms/step - loss: 587238.1250
Epoch 4/10
1/1 [==============================] - 0s 6ms/step - loss: 40780416.0000
Epoch 5/10
1/1 [==============================] - 0s 6ms/step - loss: 2831973376.0000
Epoch 6/10
1/1 [==============================] - 0s 6ms/step - loss: 196664819712.0000
Epoch 7/10
1/1 [==============================] - 0s 6ms/step - loss: 13657280872448.0000
Epoch 8/10
1/1 [==============================] - 0s 7ms/step - loss: 948422462930944.0000
Epoch 9/10
1/1 [==============================] - 0s 6ms/step - loss: 65862670649131008.0000
Epoch 10/10
1/1 [==============================] - 0s 5ms/step - loss: 4573797672367947776.0000


In [11]:
model.predict(x_train)

1/1 [==============================] - 0s 15ms/step


array([[-1.6499996e+10],
       [-8.2499978e+09],
       [ 2.4749994e+10]], dtype=float32)

In [12]:
new_values = np.array([[-10], [0], [5]])
model.predict(new_values)

1/1 [==============================] - 0s 15ms/step


array([[ 8.2499977e+10],
       [ 1.3499588e+02],
       [-4.1249989e+10]], dtype=float32)

In [13]:
model.get_weights()

[array([[-8.249998e+09]], dtype=float32), array([134.99588], dtype=float32)]

In [18]:
y_train_new = np.array([11, 6, -14])
model = Sequential()
model.add(Dense(num_neurons, input_dim = 1))
model.summary()
sgd = SGD(lr=0.1) 
model.compile(loss='mean_squared_error', optimizer=sgd)
model.fit(x_train, y_train_new, epochs=15)

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________
Epoch 1/15
1/1 [==============================] - 0s 137ms/step - loss: 63.1670
Epoch 2/15
1/1 [==============================] - 0s 6ms/step - loss: 0.9163
Epoch 3/15
1/1 [==============================] - 0s 7ms/step - loss: 0.4108
Epoch 4/15
1/1 [==============================] - 0s 6ms/step - loss: 0.2621
Epoch 5/15
1/1 [==============================] - 0s 7ms/step - loss: 0.1678
Epoch 6/15
1/1 [==============================] - 0s 7ms/step - loss: 0.1074
Epoch 7/15
1/1 [==============================] - 0s 7ms/step - loss: 0.0687
Epoch 8/15
1/1 [==============================

In [16]:
model.get_weights()

[array([[5.]], dtype=float32), array([0.9648156], dtype=float32)]